version: "3.8"

services:
  minio:
    container_name: minIO
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: dev_user
      MINIO_ROOT_PASSWORD: dev_password
    networks:
      - minio-sample
    volumes:
      - minio-storage:/data

  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    networks:
      - minio-sample
    volumes:
      - database:/var/lib/postgresql/data:rw
    depends_on: 
      - minio
    
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ConnectionStrings__PSQL=Host=database;Port=5432;Database=dev_db;Username=dev_user;Password=dev_password;"    
    ports:
      - "8080:8080"
    depends_on:
      - database
      - minio
    networks:
      - minio-sample
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  minio-storage:
  database:
    
networks:
  minio-sample:
    driver: bridge